workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

stages:
  - test
  - build

test:
  image: $IMAGE
  stage: test
  retry:
    when: script_failure
    max: 1
  script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - yapf -pr .
    - pytest --cov=./ --cov-config=.coveragerc --junitxml=$IMAGE-report.xml
  artifacts:
    when: always
    reports:
      junit: $IMAGE-report.xml
  parallel:
    matrix:
      - IMAGE:
          - "python:3.7-slim"
          - "python:3.8-slim"
          # Temporarily disable it
          # - "python:3.9-slim"

build:
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f Dockerfile.prod .
    - docker push $IMAGE_TAG
