image: python:3.7-alpine

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - yapf -r .
    - pytest
