workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

test:
  image: $IMAGE
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - yapf -pqr .
    - pytest --cov=./ --cov-config=.coveragerc --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  parallel:
    matrix:
      - IMAGE:
        - 'python:3.7-slim'
        - 'python:3.8-slim'
        # Temporarily disable it
        # - 'python:3.9-slim'
